### ISSUE TITLE
Keyboard mappings are one off for shifted buttons

### ISSUE THREAD

**Issue by jeremyweber72** [philipellisis/arduino-virtual-pinball-board#16]
Assigning a keyboard mapping to a shifted button actually sends the next key.  For instance I have assigned button 25 to send F14, but it actually sends F15.  Using the new config tool.  I also used  https://github.com/Code52/carnac to see the keys that were sent.

**Comment by philipellisis** [comment]
fixed in latest release

**Comment by jeremyweber72** [comment]
I’m not seeing the latest release.  Also the v1.18.0 release is mislabeled
in github as v1.8.0.

**Comment by philipellisis** [comment]
Just updated the release, I decided not to update the version but I just updated the exe since there was no change to the firmware. I know it's a little confusing but I hadn't officially released the new config tool yet and I thought it would be best to keep it in the same place as not many people have downloaded it from github (the version on the docs site was still pointing to the old config tool)
